name: DevSecOps Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  secret_detection:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  install_build:
    name: Install & Build
    runs-on: ubuntu-latest
    needs: secret_detection

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - name: Build Docker Image
        run: docker build -t devscops:${{ github.sha }} .

  sast:
    name: SAST
    runs-on: ubuntu-latest
    needs: install_build

    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip3 install semgrep

      - name: Run Semgrep
        run: semgrep --config=p/security-audit .

  sca:
    name: SCA
    runs-on: ubuntu-latest
    needs: install_build

    steps:
      - uses: actions/checkout@v4

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 0

  container_scan:
    name: Container Scan
    runs-on: ubuntu-latest
    needs:
      - sast
      - sca

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devscops:${{ github.sha }} .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devscops:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 0

  docker_build_push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: container_scan
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devscops:${{ github.sha }} .

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Images
        run: |
          docker tag devscops:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/devscops:${{ github.sha }}
          docker tag devscops:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/devscops:latest

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devscops:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devscops:latest

# CI

# Checkout
# ↓
# Gitleaks
# ↓
# Semgrep
# ↓
# Trivy FS
# ↓
# Tests
# ↓
# Docker Build
# ↓
# Trivy Image

# CD

# Docker Login
# ↓
# Push Docker Image
# ↓
# Deploy
